In [1]:
import pandas as pd
df = pd.read_csv('../task04_merge/merged_full_data.csv')

In [2]:
df.head(10)

,Unnamed: 0_x,campaign_id_x,channel,budget,Unnamed: 0_y,customer_id,response,Unnamed: 0,campaign_id_y,converted,amount
0,0,CMP100,Facebook,8000000,69,CUS1069,Click,NaN,NaN,NaN,NaN
1,0,CMP100,Facebook,8000000,87,CUS1087,Ignore,91.0,CMP102,NaN,100000.0
2,0,CMP100,Facebook,8000000,87,CUS1087,Ignore,99.0,CMP114,1.0,350000.0
3,0,CMP100,Facebook,8000000,99,CUS1099,View,29.0,CMP104,1.0,NaN
4,0,CMP100,Facebook,8000000,99,CUS1099,View,50.0,CMP118,1.0,350000.0
5,0,CMP100,Facebook,8000000,117,CUS1117,Ignore,41.0,CMP103,1.0,100000.0
6,0,CMP100,Facebook,8000000,117,CUS1117,Ignore,65.0,CMP108,1.0,300000.0
7,1,CMP101,TikTok,5000000,2,CUS1002,Ignore,93.0,CMP118,1.0,NaN
8,1,CMP101,TikTok,5000000,11,CUS1011,Ignore,51.0,CMP106,0.0,100000.0
9,1,CMP101,TikTok,5000000,11,CUS1011,Ignore,83.0,CMP102,1.0,350000.0

1.Pivot tỷ lệ chuyển đổi theo kênh × loại phản hồi

In [3]:
import pandas as pd

df = pd.read_csv('../task04_merge/merged_full_data.csv')

df.head()
conversion_summary = df.groupby(['channel', 'response']).agg(
    Total_Responses=('campaign_id_x', 'size'),
    Total_Conversions=('converted', 'sum')
).reset_index()

conversion_summary['Conversion_Rate'] = (
    conversion_summary['Total_Conversions'] / conversion_summary['Total_Responses']) * 100
pivot_conversion_rate = conversion_summary.pivot_table(
    index='channel',
    columns='response',
    values='Conversion_Rate',
    fill_value=0,
    margins=False,                
    dropna=True,                  
    margins_name='All',         
    observed=False               
).applymap(lambda x: f"{x:.2f}%")

print("\n--- PIVOT: TỶ LỆ CHUYỂN ĐỔI ---")
print(pivot_conversion_rate)
df.head(20)

--- PIVOT: TỶ LỆ CHUYỂN ĐỔI ---
response   Click  Ignore    View
channel
Email     50.00%  45.45%  57.14%
Facebook  45.00%  31.82%  41.18%
Google    28.57%  57.14%   0.00%
TikTok    14.29%  27.78%  40.00%

C:\Users\Admin\AppData\Local\Temp\ipykernel_12232\101858553.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ).applymap(lambda x: f"{x:.2f}%")

,Unnamed: 0_x,campaign_id_x,channel,budget,Unnamed: 0_y,customer_id,response,Unnamed: 0,campaign_id_y,converted,amount
0,0,CMP100,Facebook,8000000,69,CUS1069,Click,NaN,NaN,NaN,NaN
1,0,CMP100,Facebook,8000000,87,CUS1087,Ignore,91.0,CMP102,NaN,100000.0
2,0,CMP100,Facebook,8000000,87,CUS1087,Ignore,99.0,CMP114,1.0,350000.0
3,0,CMP100,Facebook,8000000,99,CUS1099,View,29.0,CMP104,1.0,NaN
4,0,CMP100,Facebook,8000000,99,CUS1099,View,50.0,CMP118,1.0,350000.0
5,0,CMP100,Facebook,8000000,117,CUS1117,Ignore,41.0,CMP103,1.0,100000.0
6,0,CMP100,Facebook,8000000,117,CUS1117,Ignore,65.0,CMP108,1.0,300000.0
7,1,CMP101,TikTok,5000000,2,CUS1002,Ignore,93.0,CMP118,1.0,NaN
8,1,CMP101,TikTok,5000000,11,CUS1011,Ignore,51.0,CMP106,0.0,100000.0
9,1,CMP101,TikTok,5000000,11,CUS1011,Ignore,83.0,CMP102,1.0,350000.0
10,1,CMP101,TikTok,5000000,11,CUS1011,Ignore,105.0,CMP103,0.0,200000.0
11,1,CMP101,TikTok,5000000,16,CUS1016,Click,NaN,NaN,NaN,NaN
12,1,CMP101,TikTok,5000000,27,CUS1027,View,10.0,CMP114,0.0,300000.0
13,1,CMP101,TikTok,5000000,27,CUS1027,View,100.0,CMP119,1.0,350000.0
14,1,CMP101,TikTok,5000000,64,CUS1064,Click,11.0,CMP113,NaN,NaN
15,1,CMP101,TikTok,5000000,64,CUS1064,Click,12.0,CMP116,0.0,300000.0
16,1,CMP101,TikTok,5000000,64,CUS1064,Click,68.0,CMP108,NaN,300000.0
17,2,CMP102,Facebook,7000000,18,CUS1018,Click,NaN,NaN,NaN,NaN
18,2,CMP102,Facebook,7000000,47,CUS1047,Click,46.0,CMP107,1.0,NaN
19,2,CMP102,Facebook,7000000,47,CUS1047,Click,52.0,CMP119,1.0,500000.0

2.Pivot doanh thu theo chiến dịch × kênh

In [4]:
pivot_revenue = pd.pivot_table(df, 
                               values='amount', 
                               index='campaign_id_x', 
                               columns='channel', 
                               aggfunc='mean', 
                               fill_value=0)
print("\n=== PIVOT DOANH THU THEO CHIẾN DỊCH × KÊNH ===")
print(pivot_revenue)

=== PIVOT DOANH THU THEO CHIẾN DỊCH × KÊNH ===
channel                Email       Facebook         Google         TikTok
campaign_id_x
CMP100              0.000000  240000.000000       0.000000       0.000000
CMP101              0.000000       0.000000       0.000000  271428.571429
CMP102              0.000000  316666.666667       0.000000       0.000000
CMP103              0.000000  225000.000000       0.000000       0.000000
CMP104              0.000000       0.000000  233333.333333       0.000000
CMP105              0.000000  500000.000000       0.000000       0.000000
CMP106              0.000000  305555.555556       0.000000       0.000000
CMP107              0.000000       0.000000  200000.000000       0.000000
CMP108         200000.000000       0.000000       0.000000       0.000000
CMP109              0.000000  133333.333333       0.000000       0.000000
CMP110              0.000000       0.000000  208333.333333       0.000000
CMP111              0.000000  175000.000000       0.000000       0.000000
CMP112              0.000000       0.000000       0.000000  250000.000000
CMP113              0.000000       0.000000       0.000000  270000.000000
CMP114              0.000000       0.000000       0.000000  268750.000000
CMP115         266666.666667       0.000000       0.000000       0.000000
CMP116              0.000000       0.000000       0.000000  290000.000000
CMP117         183333.333333       0.000000       0.000000       0.000000
CMP118              0.000000       0.000000  320000.000000       0.000000
CMP119              0.000000       0.000000  240000.000000       0.000000

3. Chuyển đổi stack/unstack để hiểu MultiIndex

In [5]:
# Stack: 
stacked = pivot_conversion_rate.stack()
print("\nDữ liệu sau khi stack (MultiIndex):\n", stacked)
# Unstack: 
unstacked = stacked.unstack()
print("\nDữ liệu sau khi unstack (quay về pivot):\n", unstacked)

Dữ liệu sau khi stack (MultiIndex):
 channel   response
Email     Click       50.00%
          Ignore      45.45%
          View        57.14%
Facebook  Click       45.00%
          Ignore      31.82%
          View        41.18%
Google    Click       28.57%
          Ignore      57.14%
          View         0.00%
TikTok    Click       14.29%
          Ignore      27.78%
          View        40.00%
dtype: object

Dữ liệu sau khi unstack (quay về pivot):
 response   Click  Ignore    View
channel
Email     50.00%  45.45%  57.14%
Facebook  45.00%  31.82%  41.18%
Google    28.57%  57.14%   0.00%
TikTok    14.29%  27.78%  40.00%

4. Nhận xét chiến dịch/kênh hiệu quả nhất

In [6]:
if 'Click' in pivot_conversion_rate.columns:
    best_channel = pivot_conversion_rate['Click'].str.rstrip('%').astype(float).idxmax()
    print("Kênh hiệu quả nhất:", best_channel)
best_campaign = pivot_revenue.mean(axis=1).idxmax()
print("Chiến dịch hiệu quả nhất:", best_campaign)

Kênh hiệu quả nhất: Email
Chiến dịch hiệu quả nhất: CMP105